---
provisioner:
  name: chef_zero
  sudo: true
  require_chef_omnibus: '11.16.4'

driver_plugin: joyent
driver_config:
  joyent_username: <%= ENV['MANTA_USER'] %>
  joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
  joyent_keyname: <%= ENV['MANTA_KEY_ID'] %>
  joyent_url: <%= ENV['JOYENT_API_URL'] %>
  joyent_version: '~7.0'
  joyent_networks:
    - 1e7bb0e1-25a9-43b6-bb19-f79ae9540b39
    - e9b2351c-b0b7-4388-b660-96a7dfe19566
  joyent_flavor_id: g3-highcpu-1.75-smartos
  username: root

platforms:
- name: centos-7_20150406
  driver_config:
    joyent_image_id: c41bf236-dc75-11e4-88e5-038814c07c11

- name: smartos-base64-lts_14.4.1
  driver_config:
    joyent_image_id: 24648664-e50c-11e4-be23-0349d0a5f3cf
  provisioner:
    name: chef_zero
    sudo: true
    require_chef_omnibus: true
    chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/latest.sh

suites:
  - name: circonus-broker
    run_list:
      - recipe[circonus-broker::default]
